env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
plugins:
  - vue
rules: {
  vue/multi-word-component-names: warn
}
